buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        implementation project(':FtcRobotController')
        annotationProcessor files('lib/OpModeAnnotationProcessor.jar')

        // Add this line for Road Runner
        implementation 'com.acmerobotics.roadrunner:core:0.5.6'
    }
}
